### ISSUE TITLE
Trapdoor

### ISSUE THREAD

**Issue by 0xtf** [lonestarlabs/Awesome-Deception-Technology#1]
Hi,

Didn't do a PR as I wasn't sure if it fits on the list but thought I'd ask. We recently released Trapdoor, an AWS-based serverless honeytoken framework:

* https://twitter.com/3CORESec/status/1374405185452134413

**Comment by tolgadevsec** [comment]
Hey there!
Apologies for not taking notice of your request for such a long time. This looks really interesting and the blog post would fit into the list ;)
Kind regards,
Tolga
